// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJy7qVpU0EG3LhgBOaEIBSb6QkVpy3Ro',
    appId: '1:231818387263:web:d03064ed0fc49ce221fd8a',
    messagingSenderId: '231818387263',
    projectId: 'rtx-alert-app-b343c',
    authDomain: 'rtx-alert-app-b343c.firebaseapp.com',
    storageBucket: 'rtx-alert-app-b343c.appspot.com',
    measurementId: 'G-7Z0THNG19K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-1YgAOjs6nepzwkd6Artw7JisnywkME',
    appId: '1:231818387263:android:d1f34087c6d9529321fd8a',
    messagingSenderId: '231818387263',
    projectId: 'rtx-alert-app-b343c',
    storageBucket: 'rtx-alert-app-b343c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UL0KB9i9u_jytTsCBfrP2d6jZQEpGx4',
    appId: '1:231818387263:ios:34e73faa9a935b1a21fd8a',
    messagingSenderId: '231818387263',
    projectId: 'rtx-alert-app-b343c',
    storageBucket: 'rtx-alert-app-b343c.appspot.com',
    iosBundleId: 'com.example.rtxAlertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UL0KB9i9u_jytTsCBfrP2d6jZQEpGx4',
    appId: '1:231818387263:ios:d05c0c4cb06e408b21fd8a',
    messagingSenderId: '231818387263',
    projectId: 'rtx-alert-app-b343c',
    storageBucket: 'rtx-alert-app-b343c.appspot.com',
    iosBundleId: 'com.example.rtxAlertApp.RunnerTests',
  );
}
